version: '3.7'

services:
  ssbswang-portfolio:
    container_name: 'ssbswang-portfolio'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    logging:
      driver: awslogs
      options:
        awslogs-group: "mmm-logs"
        awslogs-region: "us-east-1"
        awslogs-create-group: "true"

